# This is a basic workflow to help you get started with Actions

name: Release macos

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags:
      - "v*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Uses NodeJs Environment
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - name: install dependencies
        run: yarn

      - name: build macos x64
        run: yarn electron:build

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1

      - name: Archive Release
        run: zip -r  -o 'macos_x64_MathFX_${{steps.tag.outputs.tag}}.zip' './dist_electron/'

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "macos_x64_MathFX_${{steps.tag.outputs.tag}}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
